{{
    config(
        materialized = 'incremental',
        unique_key='ID',
        schema = 'Data_Mart',
        incremental_strategy='merge',
        merge_update_columns = ['ID','ISDELETED','MASTERRECORDID','NAME','TYPE','RECORDTYPEID','PARENTID','BILLINGSTREET',
        'BILLINGCITY','BILLINGSTATE','BILLINGPOSTALCODE','BILLINGCOUNTRY', 'BILLINGSTATECODE',
        'BILLINGCOUNTRYCODE','BILLINGLATITUDE','BILLINGLONGITUDE','BILLINGGEOCODEACCURACY',
        'SHIPPINGSTREET','SHIPPINGCITY','SHIPPINGSTATE','SHIPPINGPOSTALCODE','SHIPPINGCOUNTRY',
        'SHIPPINGSTATECODE', 'SHIPPINGCOUNTRYCODE','SHIPPINGLATITUDE','SHIPPINGLONGITUDE',
        'SHIPPINGGEOCODEACCURACY','PHONE','FAX','WEBSITE','PHOTOURL','SIC','INDUSTRY','ANNUALREVENUE',
        'NUMBEROFEMPLOYEES','OWNERSHIP','TICKERSYMBOL','DESCRIPTION','SITE','OWNERID','CREATEDDATE','CREATEDBYID',
        'LASTMODIFIEDDATE','LASTMODIFIEDBYID','SYSTEMMODSTAMP','LASTACTIVITYDATE','LASTVIEWEDDATE',
        'LASTREFERENCEDDATE','ISPARTNER','ISCUSTOMERPORTAL','JIGSAW','JIGSAWCOMPANYID',
        'ACCOUNTSOURCE','SICDESC','DANDBCOMPANYID','OPERATINGHOURSID','DW_KEY_ID','DW_UPDATE_DT'],
        post_hook="Update skilful-gantry-404609.Landing.INFOFISCUS_CT CT SET LAST_RUN_DATE = CURRENT_TIMESTAMP() WHERE
        SRC_OBJECT =  'ACCOUNTS' AND TGT_OBJECT = 'STG_ACCOUNTS' ;"
    )
}}

SELECT 
ID,ISDELETED,MASTERRECORDID,NAME,TYPE,NULL AS RECORDTYPEID,PARENTID, null as BILLINGSTREET,
        BILLINGCITY,BILLINGSTATE,BILLINGPOSTALCODE,BILLINGCOUNTRY, NULL AS BILLINGSTATECODE,
        NULL AS BILLINGCOUNTRYCODE,BILLINGLATITUDE,BILLINGLONGITUDE,BILLINGGEOCODEACCURACY,
        null as SHIPPINGSTREET,SHIPPINGCITY,SHIPPINGSTATE,SHIPPINGPOSTALCODE,SHIPPINGCOUNTRY,
        NULL AS SHIPPINGSTATECODE, NULL AS SHIPPINGCOUNTRYCODE,SHIPPINGLATITUDE,SHIPPINGLONGITUDE,
        SHIPPINGGEOCODEACCURACY,PHONE,FAX,WEBSITE,PHOTOURL,SIC,INDUSTRY,ANNUALREVENUE,
        NUMBEROFEMPLOYEES,OWNERSHIP,TICKERSYMBOL,null as DESCRIPTION,SITE,OWNERID,CREATEDDATE,CREATEDBYID,
        LASTMODIFIEDDATE,LASTMODIFIEDBYID,SYSTEMMODSTAMP,LASTACTIVITYDATE,LASTVIEWEDDATE,
        LASTREFERENCEDDATE,NULL AS ISPARTNER,NULL AS ISCUSTOMERPORTAL,JIGSAW,JIGSAWCOMPANYID,
        ACCOUNTSOURCE,SICDESC,DANDBCOMPANYID,OPERATINGHOURSID, ID AS DW_KEY_ID,     
CURRENT_TIMESTAMP AS DW_INSERT_DT, CURRENT_TIMESTAMP AS DW_UPDATE_DT
FROM {{ref('STG_ACCOUNTS')}}
            