

{{
    config(
        materialized = 'incremental',
        unique_key='ID',
        incremental_strategy='merge',
        schema = 'Data_Mart',
        merge_update_columns = ["ID","ISDELETED","NAME","PARENTID","RECORDTYPEID","TYPE","STATUS","STARTDATE","ENDDATE",
        "EXPECTEDREVENUE","BUDGETEDCOST","ACTUALCOST","CAMPAIGNIMAGEID","EXPECTEDRESPONSE","NUMBERSENT",
        "ISACTIVE","DESCRIPTION","NUMBEROFLEADS","NUMBEROFCONVERTEDLEADS","NUMBEROFCONTACTS","NUMBEROFRESPONSES",
        "NUMBEROFOPPORTUNITIES","NUMBEROFWONOPPORTUNITIES","AMOUNTALLOPPORTUNITIES","AMOUNTWONOPPORTUNITIES",
        "CURRENCYISOCODE","OWNERID", "TENANTID","CREATEDDATE","CREATEDBYID","LASTMODIFIEDDATE",
        "LASTMODIFIEDBYID","SYSTEMMODSTAMP","LASTACTIVITYDATE","LASTVIEWEDDATE","LASTREFERENCEDDATE",
        "CAMPAIGNMEMBERRECORDTYPEID", "DW_UPDATE_DT"]
    )
}}

SELECT {{ generate_surrogate_key(['ID']) }} as CAMPAIGN_KEY,
ID,ISDELETED,NAME,PARENTID,NULL AS RECORDTYPEID,TYPE,STATUS,STARTDATE,ENDDATE,
EXPECTEDREVENUE,BUDGETEDCOST,ACTUALCOST,NULL AS CAMPAIGNIMAGEID,EXPECTEDRESPONSE,NUMBERSENT,
ISACTIVE,DESCRIPTION,NUMBEROFLEADS,NUMBEROFCONVERTEDLEADS,NUMBEROFCONTACTS,NUMBEROFRESPONSES,
NUMBEROFOPPORTUNITIES,NUMBEROFWONOPPORTUNITIES,AMOUNTALLOPPORTUNITIES,AMOUNTWONOPPORTUNITIES,
NULL AS CURRENCYISOCODE,OWNERID, NULL AS TENANTID,CREATEDDATE,CREATEDBYID,LASTMODIFIEDDATE,
LASTMODIFIEDBYID,SYSTEMMODSTAMP,LASTACTIVITYDATE,LASTVIEWEDDATE,LASTREFERENCEDDATE,
CAMPAIGNMEMBERRECORDTYPEID,
CURRENT_TIMESTAMP AS INSERT_DT, ID AS KEY_ID,         
CURRENT_TIMESTAMP AS DW_INSERT_DT, CURRENT_TIMESTAMP AS DW_UPDATE_DT
FROM {{ref('STG_CAMPAIGNS')}}