
version: 2

sources:
  - name: Infofiscus
    database: skilful-gantry-404609
    schema: Landing   
    tables: 
      - name: ACCOUNTS
      - name: CAMPAIGNS
 
  - name: source_name 
    database: |
      {%- if  target.name == "DBT_PROD" -%} 	prod-406711
      {%- elif target.name == "Development"  -%} skilful-gantry-404609
      {%- else -%} invalid_database
      {%- endif -%}
    schema: source_schema